---
title: "Specta Pedis"
layout: post
categories:
  - Daily Life
---
<p><span style="color: #800000;">In today&rsquo;s devotional reading I came across Isaiah chapter 52, verse 7. It reads, &ldquo;How beautiful upon the mountains are the feet of the messenger who announces peace, who brings good news, who announces salvation, who says to Zion, &lsquo;Your God reigns.&rsquo;&rdquo;</span></p>
<p><span style="color: #800000;">I came home to the states for tenth grade. It was a furlough year, when my parents did a lot of traveling around the country visiting their supporting churches. Our home base was in East Brookfield, MA, and my brother and I attended the same school district that we&rsquo;d gone to as elementary children back before my parents became missionaries. It was my brother&rsquo;s senior year.</span></p>
<p><span style="color: #800000;">When it was time to choose a foreign language to study, I chose French for an easy A. I pretty much spent the year correcting my poor teacher&rsquo;s accent and teaching her new words. My best friend was taking Latin. We tried to teach each other some phrases but nothing really stuck. Except for two words: specta pedis. It means &ldquo;Look at the feet.&rdquo;</span></p>
<p><span style="color: #800000;">My boyfriend at the time had little feet stickers stuck onto his guitar. My friend, in the process of studying her flashcards, pointed to the feet and said, &ldquo;Specta pedis.&rdquo; It turned into one of those often repeated inside jokes, and those two Latin words became firmly ensconced in my vocabulary.</span></p>
<p><span style="color: #800000;">Can you see where I&rsquo;m going here? Did you notice how these two stories fit together? When I was reading the passage in Isaiah, I had this picture in my head of someone saying, &ldquo;Specta pedis,&rdquo; and looking at the feet of messenger climbing the mountains to bring peace and good news to the men, women, and children there. How beautiful are the feet of that messenger.</span></p>
<p><span style="color: #800000;">I&rsquo;ve never seen any feet that I would classify as beautiful. And really I don&rsquo;t want anyone looking at my feet after I&rsquo;ve hiked up a mountain. But do I understand the idea. When you&rsquo;re miserable, alone, or depressed and someone brings you news that can rock your world and solve your problems, they are beautiful.</span></p>
<p><span style="color: #800000;">Wes (who created and helps maintain my website) asked me to write up a paragraph explaining the name of my blog and my goals and purposes for the website.</span></p>
<p><span style="color: #800000;">I named the website scribblinghope for a couple of reasons. The first is most obvious &ndash; anyone who&rsquo;s seen my handwriting would definitely describe it as a bit of a scribble. I sometimes call it chicken scratching. But I also like the word scribble because scribbling implies that it&rsquo;s not always carefully crafted and thought out. It&rsquo;s not professional. It&rsquo;s not perfect. Sometimes my writing is messy and chaotic. This isn&rsquo;t a formal site meant to look perfectly polished. It&rsquo;s just a bit of a scribble as I put my thoughts out there for the world to read. But the end goal is hope. I&rsquo;m hoping that my words will bring a bit of Hope into a tired world. That somehow, by sharing my thoughts, I can light a candle in someone else&rsquo;s darkness. That maybe my story will remind someone else that their story can be amazingly beautiful. And that together, our stories can change our worlds. I want to use my scribbling to share Hope, announce Peace, bring Good News, and announce Salvation.</span></p>
<p><span style="color: #800000;">I want to have beautiful feet.</span></p>
